### ISSUE TITLE
cli middleware broken in 0.3 

### ISSUE THREAD

**Issue by pgherveou** [qualiancy/kinetik#22]
I have this stack trace when using cli middleware with 0.3

```
node_modules/kinetik/lib/kinetik/middleware/cli.js:23
    program.opts.base = 'node ' + name;
                      ^
TypeError: Cannot set property 'base' of undefined
    at module.exports (node_modules/kinetik/lib/kinetik/middleware/cli.js:23:23)
    at Queue.use (node_modules/kinetik/lib/kinetik/queue.js:174:5)
    at Object.<anonymous> (/Users/pg/SQ/sq_app/jobs.js:27:9)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
```

**Comment by logicalparadox** [comment]
Update to 0.3.1
